name: Automated Testing Workflow

on: [push]

jobs:
  test-application:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Test 1 - Multiple Numbers
        run: |
          python find_lowest_number.py test_data/test1_input.txt test_output1.txt
      
      - name: Test 2 - Single Number
        run: |
          python find_lowest_number.py test_data/test2_input.txt test_output2.txt
      
      - name: Test 3 - Blank File
        run: |
          python find_lowest_number.py test_data/test3_input.txt test_output3.txt

      - name: Compare Output 1
        run: diff --ignore-all-space test_output1.txt test_data/test1_expected.txt
        
      - name: Compare Output 2
        run: diff --ignore-all-space test_output2.txt test_data/test2_expected.txt

      - name: Compare Output 3
        run: diff --ignore-all-space test_output3.txt test_data/test3_expected.txt

      - name: Upload Output Files as Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-output-files
          path: |
            test_output1.txt
            test_output2.txt
            test_output3.txt
